version: 2
jobs:
  build1:
    working_directory: /go/src/github.com/wsgk/Docker-circleci-test
    docker:
      - image: circleci/golang
    steps:
      - checkout
  build2:
    working_directory: /go/src/github.com/wsgk/Docker-circleci-test
    docker:
      - image: vvakame/circleci-gaego
    steps:
      - checkout
  build3:
    working_directory: /go/src/github.com/wsgk/Docker-circleci-test
    docker:
      - image: mercari/appengine-go
    steps:
      - checkout
